// Mock Data Service - Comprehensive dummy data for all endpoints
// Simulates API delays for realism

const delay = (ms: number = 100) => new Promise(resolve => setTimeout(resolve, ms));

// Mock user data
export const mockUser = {
  id: 1,
  email: 'mahmut@turan.com',
  name: 'Mahmut Turan',
  role: 'admin',
  department: 'Audit',
  status: 'active' as const,
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

export const mockPermissions = {
  charts: [
    { chart_name: 'audit-projects-by-year', can_view: true, can_export: true },
    { chart_name: 'investigations-by-year', can_view: true, can_export: true },
    { chart_name: 'finding-status-by-year', can_view: true, can_export: true },
  ],
  tasks: {
    can_view: true,
    can_create: true,
    can_edit: true,
    can_delete: true,
  },
  pages: ['dashboard', 'tasks', 'my-actions', 'audit-findings', 'annual-audit-plan'],
  components: [
    'dashboard_page',
    'my_actions_page',
    'department_actions_page',
    'clevel_actions_page',
    'management_actions_page',
    'all_findings_actions_page',
    'annual_audit_plan_page',
    'audit_universe_page',
    'risk_management_page',
    'audit_maturity_page',
    'task_manager',
    'access_management',
    'audit_finding_page',
  ],
  interactiveComponents: ['*'],
};

// Mock chart data
export const mockChartData = {
  'audit-projects-by-year': {
    labels: ['2020', '2021', '2022', '2023', '2024', '2025'],
    datasets: [{
      label: 'Audit Projects',
      data: [12, 15, 18, 22, 25, 20],
      backgroundColor: 'rgba(99, 102, 241, 0.5)',
      borderColor: 'rgba(99, 102, 241, 1)',
      borderWidth: 2,
    }],
  },
  'investigation-counts': {
    total: 45,
    open: 12,
    closed: 33,
    inProgress: 8,
  },
  'finding-status-by-year': {
    '2024': {
      'Open': 15,
      'In Progress': 8,
      'Closed': 22,
      'Risk Accepted': 3,
    },
    '2025': {
      'Open': 12,
      'In Progress': 10,
      'Closed': 18,
      'Risk Accepted': 2,
    },
  },
  'finding-action-status-distribution': {
    labels: ['Open', 'In Progress', 'Closed', 'Risk Accepted'],
    datasets: [{
      label: 'Actions',
      data: [25, 18, 45, 5],
      backgroundColor: [
        'rgba(239, 68, 68, 0.5)',
        'rgba(251, 191, 36, 0.5)',
        'rgba(34, 197, 94, 0.5)',
        'rgba(107, 114, 128, 0.5)',
      ],
    }],
  },
  'actions-by-audit-and-risk': [
    { auditYear: '2024', auditName: 'Financial Audit', riskLevel: 'High', count: 12 },
    { auditYear: '2024', auditName: 'Financial Audit', riskLevel: 'Medium', count: 8 },
    { auditYear: '2024', auditName: 'Operational Audit', riskLevel: 'High', count: 15 },
    { auditYear: '2025', auditName: 'IT Audit', riskLevel: 'High', count: 10 },
  ],
  'findings-by-audit-and-risk': [
    { auditYear: '2024', auditName: 'Financial Audit', riskLevel: 'High', count: 8 },
    { auditYear: '2024', auditName: 'Operational Audit', riskLevel: 'Medium', count: 12 },
  ],
  'finding-actions-aging': {
    labels: ['0-30 days', '31-60 days', '61-90 days', '91-180 days', '180+ days'],
    datasets: [{
      label: 'Actions',
      data: [15, 12, 8, 5, 3],
      backgroundColor: 'rgba(239, 68, 68, 0.5)',
    }],
  },
  'fraud-impact-score-cards': {
    '2024+': {
      openFinancialImpact: 125000,
      overdueFinancialImpact: 45000,
      totalFinancialImpact: 170000,
    },
    'all': {
      openFinancialImpact: 250000,
      overdueFinancialImpact: 85000,
      totalFinancialImpact: 335000,
    },
  },
  'lp-impact-score-cards': {
    '2024+': {
      openFinancialImpact: 98000,
      overdueFinancialImpact: 32000,
      totalFinancialImpact: 130000,
    },
    'all': {
      openFinancialImpact: 180000,
      overdueFinancialImpact: 65000,
      totalFinancialImpact: 245000,
    },
  },
  'mat-scores': {
    '2024': {
      overall: 3.8,
      categories: {
        'Governance': 4.2,
        'Risk Management': 3.9,
        'Control Environment': 3.7,
        'Monitoring': 3.6,
        'Communication': 4.0,
      },
    },
    '2025': {
      overall: 4.1,
      categories: {
        'Governance': 4.4,
        'Risk Management': 4.2,
        'Control Environment': 4.0,
        'Monitoring': 3.9,
        'Communication': 4.2,
      },
    },
  },
  'radar-chart-data': {
    labels: ['Governance', 'Risk Management', 'Control Environment', 'Monitoring', 'Communication'],
    datasets: [{
      label: '2024',
      data: [4.2, 3.9, 3.7, 3.6, 4.0],
      borderColor: 'rgba(99, 102, 241, 1)',
      backgroundColor: 'rgba(99, 102, 241, 0.2)',
    }, {
      label: '2025',
      data: [4.4, 4.2, 4.0, 3.9, 4.2],
      borderColor: 'rgba(34, 197, 94, 1)',
      backgroundColor: 'rgba(34, 197, 94, 0.2)',
    }],
  },
  'finding-risk-distribution-by-project': [
    { project: 'Financial Audit 2024', high: 5, medium: 8, low: 3 },
    { project: 'IT Audit 2024', high: 3, medium: 6, low: 2 },
    { project: 'Operational Audit 2024', high: 7, medium: 10, low: 4 },
  ],
  'action-age-distribution': {
    labels: ['0-30', '31-60', '61-90', '91-180', '180+'],
    datasets: [{
      label: 'Actions',
      data: [20, 15, 10, 8, 5],
      backgroundColor: 'rgba(99, 102, 241, 0.5)',
    }],
  },
  'lead-status-distribution': {
    '2024+': {
      'Open': 25,
      'In Progress': 18,
      'Closed': 45,
      'Risk Accepted': 5,
    },
    'all': {
      'Open': 45,
      'In Progress': 32,
      'Closed': 88,
      'Risk Accepted': 12,
    },
  },
  'project-risk-distribution': {
    labels: ['High', 'Medium', 'Low'],
    datasets: [{
      label: 'Projects',
      data: [15, 28, 12],
      backgroundColor: [
        'rgba(239, 68, 68, 0.5)',
        'rgba(251, 191, 36, 0.5)',
        'rgba(34, 197, 94, 0.5)',
      ],
    }],
  },
  'department-stats': {
    totalActions: 93,
    openActions: 25,
    closedActions: 58,
    overdueActions: 12,
    upcomingActions: 8,
  },
  'control-element-distribution': [
    { controlElement: 'Control Environment', high: 5, medium: 8, low: 2 },
    { controlElement: 'Risk Assessment', high: 3, medium: 6, low: 1 },
    { controlElement: 'Control Activities', high: 7, medium: 10, low: 3 },
  ],
  'risk-type-distribution': [
    { riskType: 'Financial', high: 8, medium: 12, low: 3 },
    { riskType: 'Operational', high: 6, medium: 10, low: 4 },
    { riskType: 'Compliance', high: 4, medium: 7, low: 2 },
  ],
  'fraud-internal-control': {
    result: [
      ['Category', 'Count', 'Impact'],
      ['Fraud Detection', '12', '€125,000'],
      ['Internal Control', '8', '€85,000'],
      ['Risk Management', '15', '€95,000'],
    ],
  },
  'loss-prevention-summary': {
    result: [
      ['Period', 'Incidents', 'Loss Amount'],
      ['Q1 2024', '5', '€45,000'],
      ['Q2 2024', '8', '€62,000'],
      ['Q3 2024', '6', '€48,000'],
      ['Q4 2024', '4', '€35,000'],
    ],
  },
};

// Mock finding actions - comprehensive list
export const mockFindingActions = [
  {
    key: 'AUDIT-1001',
    summary: 'Implement enhanced financial controls',
    description: 'Review and strengthen financial control procedures',
    status: 'Open',
    displayStatus: 'Open',
    dueDate: '2025-03-15',
    responsible: 'john.doe@example.com',
    responsibleEmail: 'john.doe@example.com',
    cLevel: 'CFO',
    auditYear: '2024',
    auditName: 'Financial Audit',
    riskLevel: 'High',
  },
  {
    key: 'AUDIT-1002',
    summary: 'Update IT security policies',
    description: 'Review and update IT security documentation',
    status: 'In Progress',
    displayStatus: 'In Progress',
    dueDate: '2025-02-28',
    responsible: 'jane.smith@example.com',
    responsibleEmail: 'jane.smith@example.com',
    cLevel: 'CTO',
    auditYear: '2024',
    auditName: 'IT Audit',
    riskLevel: 'Medium',
  },
  {
    key: 'AUDIT-1003',
    summary: 'Improve operational procedures',
    description: 'Enhance operational workflow documentation',
    status: 'Closed',
    displayStatus: 'Closed',
    dueDate: '2024-12-31',
    responsible: 'bob.wilson@example.com',
    responsibleEmail: 'bob.wilson@example.com',
    auditYear: '2024',
    auditName: 'Operational Audit',
    riskLevel: 'Medium',
  },
  {
    key: 'AUDIT-1004',
    summary: 'Enhance compliance monitoring',
    description: 'Implement automated compliance monitoring system',
    status: 'Open',
    displayStatus: 'Open',
    dueDate: '2025-04-10',
    responsible: 'alice.brown@example.com',
    responsibleEmail: 'alice.brown@example.com',
    auditYear: '2024',
    auditName: 'Compliance Audit',
    riskLevel: 'High',
  },
  {
    key: 'AUDIT-1005',
    summary: 'Update risk assessment framework',
    description: 'Review and update enterprise risk assessment methodology',
    status: 'In Progress',
    displayStatus: 'In Progress',
    dueDate: '2025-03-20',
    responsible: 'charlie.davis@example.com',
    responsibleEmail: 'charlie.davis@example.com',
    auditYear: '2024',
    auditName: 'Risk Management Audit',
    riskLevel: 'High',
  },
  {
    key: 'AUDIT-1006',
    summary: 'Strengthen data privacy controls',
    description: 'Implement GDPR compliance measures',
    status: 'Open',
    displayStatus: 'Open',
    dueDate: '2025-05-01',
    responsible: 'diana.evans@example.com',
    responsibleEmail: 'diana.evans@example.com',
    auditYear: '2024',
    auditName: 'Data Privacy Audit',
    riskLevel: 'Medium',
  },
  {
    key: 'AUDIT-1007',
    summary: 'Improve vendor management process',
    description: 'Enhance vendor onboarding and monitoring procedures',
    status: 'Closed',
    displayStatus: 'Closed',
    dueDate: '2024-11-15',
    responsible: 'frank.garcia@example.com',
    responsibleEmail: 'frank.garcia@example.com',
    auditYear: '2024',
    auditName: 'Vendor Management Audit',
    riskLevel: 'Low',
  },
  {
    key: 'AUDIT-1008',
    summary: 'Update business continuity plan',
    description: 'Review and test business continuity procedures',
    status: 'Open',
    displayStatus: 'Open',
    dueDate: '2025-06-30',
    responsible: 'grace.harris@example.com',
    responsibleEmail: 'grace.harris@example.com',
    auditYear: '2024',
    auditName: 'Business Continuity Audit',
    riskLevel: 'High',
  },
  // More actions for comprehensive data
  {
    key: 'AUDIT-1009',
    summary: 'Enhance vendor risk assessment',
    description: 'Implement comprehensive vendor risk evaluation process',
    status: 'In Progress',
    displayStatus: 'In Progress',
    dueDate: '2025-04-20',
    responsible: 'henry.irwin@example.com',
    responsibleEmail: 'henry.irwin@example.com',
    auditYear: '2024',
    auditName: 'Vendor Management Audit',
    riskLevel: 'Medium',
  },
  {
    key: 'AUDIT-1010',
    summary: 'Improve internal audit documentation',
    description: 'Standardize audit documentation templates',
    status: 'Closed',
    displayStatus: 'Closed',
    dueDate: '2024-10-15',
    responsible: 'ivy.jackson@example.com',
    responsibleEmail: 'ivy.jackson@example.com',
    auditYear: '2024',
    auditName: 'Internal Audit',
    riskLevel: 'Low',
  },
  {
    key: 'AUDIT-1011',
    summary: 'Strengthen cybersecurity framework',
    description: 'Enhance cybersecurity controls and monitoring',
    status: 'Open',
    displayStatus: 'Open',
    dueDate: '2025-05-10',
    responsible: 'jack.kelly@example.com',
    responsibleEmail: 'jack.kelly@example.com',
    cLevel: 'CTO',
    auditYear: '2024',
    auditName: 'Cybersecurity Audit',
    riskLevel: 'High',
  },
  {
    key: 'AUDIT-1012',
    summary: 'Update procurement policies',
    description: 'Review and enhance procurement procedures',
    status: 'In Progress',
    displayStatus: 'In Progress',
    dueDate: '2025-03-30',
    responsible: 'karen.lee@example.com',
    responsibleEmail: 'karen.lee@example.com',
    auditYear: '2024',
    auditName: 'Procurement Audit',
    riskLevel: 'Medium',
  },
  // More actions for comprehensive testing
  {
    key: 'AUDIT-1013',
    summary: 'Implement automated compliance monitoring',
    description: 'Deploy automated compliance monitoring system',
    status: 'Open',
    displayStatus: 'Open',
    dueDate: '2025-05-15',
    responsible: 'lisa.martinez@example.com',
    responsibleEmail: 'lisa.martinez@example.com',
    auditYear: '2024',
    auditName: 'Compliance Audit',
    riskLevel: 'High',
  },
  {
    key: 'AUDIT-1014',
    summary: 'Enhance data backup procedures',
    description: 'Improve data backup and recovery processes',
    status: 'Closed',
    displayStatus: 'Closed',
    dueDate: '2024-11-30',
    responsible: 'mike.nelson@example.com',
    responsibleEmail: 'mike.nelson@example.com',
    auditYear: '2024',
    auditName: 'IT Infrastructure Audit',
    riskLevel: 'Medium',
  },
  {
    key: 'AUDIT-1015',
    summary: 'Strengthen access control mechanisms',
    description: 'Implement multi-factor authentication across systems',
    status: 'In Progress',
    displayStatus: 'In Progress',
    dueDate: '2025-04-20',
    responsible: 'nancy.owen@example.com',
    responsibleEmail: 'nancy.owen@example.com',
    auditYear: '2024',
    auditName: 'IT Security Audit 2024',
    riskLevel: 'High',
  },
  {
    key: 'AUDIT-1016',
    summary: 'Improve incident response procedures',
    description: 'Enhance security incident response and reporting',
    status: 'Open',
    displayStatus: 'Open',
    dueDate: '2025-06-01',
    responsible: 'oscar.peterson@example.com',
    responsibleEmail: 'oscar.peterson@example.com',
    auditYear: '2024',
    auditName: 'IT Security Audit 2024',
    riskLevel: 'High',
  },
  {
    key: 'AUDIT-1017',
    summary: 'Update vendor contract templates',
    description: 'Standardize vendor contract terms and conditions',
    status: 'Closed',
    displayStatus: 'Closed',
    dueDate: '2024-10-15',
    responsible: 'patricia.quinn@example.com',
    responsibleEmail: 'patricia.quinn@example.com',
    auditYear: '2024',
    auditName: 'Vendor Management Audit',
    riskLevel: 'Low',
  },
  {
    key: 'AUDIT-1018',
    summary: 'Enhance fraud detection algorithms',
    description: 'Implement machine learning for fraud detection',
    status: 'In Progress',
    displayStatus: 'In Progress',
    dueDate: '2025-05-30',
    responsible: 'quinn.richards@example.com',
    responsibleEmail: 'quinn.richards@example.com',
    auditYear: '2024',
    auditName: 'Fraud Investigation 2024',
    riskLevel: 'High',
  },
  {
    key: 'AUDIT-1019',
    summary: 'Improve employee training programs',
    description: 'Develop comprehensive security awareness training',
    status: 'Open',
    displayStatus: 'Open',
    dueDate: '2025-07-15',
    responsible: 'rachel.stewart@example.com',
    responsibleEmail: 'rachel.stewart@example.com',
    auditYear: '2024',
    auditName: 'HR Compliance Audit',
    riskLevel: 'Medium',
  },
  {
    key: 'AUDIT-1020',
    summary: 'Strengthen network security controls',
    description: 'Implement advanced network monitoring and protection',
    status: 'Open',
    displayStatus: 'Open',
    dueDate: '2025-08-01',
    responsible: 'steve.thomas@example.com',
    responsibleEmail: 'steve.thomas@example.com',
    cLevel: 'CTO',
    auditYear: '2024',
    auditName: 'IT Security Audit 2024',
    riskLevel: 'High',
  },
  // 2025 Actions
  {
    key: 'AUDIT-2001',
    summary: 'Cloud infrastructure security hardening',
    description: 'Enhance cloud security configurations and monitoring',
    status: 'Open',
    displayStatus: 'Open',
    dueDate: '2025-09-15',
    responsible: 'tina.underwood@example.com',
    responsibleEmail: 'tina.underwood@example.com',
    auditYear: '2025',
    auditName: 'Cloud Security Audit 2025',
    riskLevel: 'High',
  },
  {
    key: 'AUDIT-2002',
    summary: 'Supply chain risk assessment framework',
    description: 'Develop comprehensive supply chain risk management',
    status: 'In Progress',
    displayStatus: 'In Progress',
    dueDate: '2025-08-30',
    responsible: 'victor.vega@example.com',
    responsibleEmail: 'victor.vega@example.com',
    auditYear: '2025',
    auditName: 'Supply Chain Risk Audit',
    riskLevel: 'Medium',
  },
  {
    key: 'AUDIT-2003',
    summary: 'API security enhancement',
    description: 'Implement API authentication and rate limiting',
    status: 'Open',
    displayStatus: 'Open',
    dueDate: '2025-10-01',
    responsible: 'wendy.walker@example.com',
    responsibleEmail: 'wendy.walker@example.com',
    auditYear: '2025',
    auditName: 'API Security Audit',
    riskLevel: 'High',
  },
  {
    key: 'AUDIT-2004',
    summary: 'Third-party risk standardization',
    description: 'Standardize third-party vendor risk assessment process',
    status: 'Open',
    displayStatus: 'Open',
    dueDate: '2025-09-20',
    responsible: 'xavier.yang@example.com',
    responsibleEmail: 'xavier.yang@example.com',
    auditYear: '2025',
    auditName: 'Third-Party Risk Audit',
    riskLevel: 'Medium',
  },
  // Department-specific actions
  {
    key: 'AUDIT-3001',
    summary: 'Department process optimization',
    description: 'Review and optimize department workflows and procedures',
    status: 'Open',
    displayStatus: 'Open',
    dueDate: '2025-04-15',
    responsible: 'dept1.director@example.com',
    responsibleEmail: 'dept1.director@example.com',
    auditYear: '2024',
    auditName: 'Department Audit',
    riskLevel: 'Medium',
  },
  {
    key: 'AUDIT-3002',
    summary: 'Department resource allocation review',
    description: 'Assess and optimize resource distribution within department',
    status: 'In Progress',
    displayStatus: 'In Progress',
    dueDate: '2025-03-25',
    responsible: 'dept2.director@example.com',
    responsibleEmail: 'dept2.director@example.com',
    auditYear: '2024',
    auditName: 'Department Audit',
    riskLevel: 'Low',
  },
  {
    key: 'AUDIT-3003',
    summary: 'Department compliance training',
    description: 'Implement department-wide compliance training program',
    status: 'Open',
    displayStatus: 'Open',
    dueDate: '2025-05-10',
    responsible: 'dept3.director@example.com',
    responsibleEmail: 'dept3.director@example.com',
    auditYear: '2024',
    auditName: 'Department Audit',
    riskLevel: 'Medium',
  },
  {
    key: 'AUDIT-3004',
    summary: 'Department performance metrics',
    description: 'Establish and monitor department performance KPIs',
    status: 'Closed',
    displayStatus: 'Closed',
    dueDate: '2024-12-20',
    responsible: 'dept4.director@example.com',
    responsibleEmail: 'dept4.director@example.com',
    auditYear: '2024',
    auditName: 'Department Audit',
    riskLevel: 'Low',
  },
  {
    key: 'AUDIT-3005',
    summary: 'Department budget optimization',
    description: 'Review and optimize department budget allocation',
    status: 'In Progress',
    displayStatus: 'In Progress',
    dueDate: '2025-04-30',
    responsible: 'dept5.director@example.com',
    responsibleEmail: 'dept5.director@example.com',
    auditYear: '2024',
    auditName: 'Department Audit',
    riskLevel: 'Medium',
  },
  // More department actions (50+ total)
  ...Array.from({ length: 45 }, (_, i) => {
    const deptNum = (i % 5) + 1;
    const statuses = ['Open', 'In Progress', 'Closed', 'Overdue'];
    const riskLevels = ['High', 'Medium', 'Low'];
    const auditYears = ['2024', '2025'];
    const status = statuses[i % statuses.length];
    const riskLevel = riskLevels[i % riskLevels.length];
    const auditYear = auditYears[i % auditYears.length];
    const dueDate = new Date(2025, 3 + (i % 6), 1 + (i % 28)).toISOString().split('T')[0];
    
    return {
      key: `AUDIT-3${String(1006 + i).padStart(3, '0')}`,
      summary: `Department ${deptNum} action ${i + 1}`,
      description: `Department ${deptNum} specific action item ${i + 1} for process improvement`,
      status,
      displayStatus: status,
      dueDate,
      responsible: `dept${deptNum}.director@example.com`,
      responsibleEmail: `dept${deptNum}.director@example.com`,
      auditYear,
      auditName: `Department ${deptNum} Audit`,
      riskLevel,
    };
  }),
  // My Actions - 100+ actions for 3-4 team_manager users
  ...Array.from({ length: 100 }, (_, i) => {
    const managerNum = (i % 4) + 1;
    const managers = [
      { email: 'manager1@example.com', name: 'Manager One' },
      { email: 'manager2@example.com', name: 'Manager Two' },
      { email: 'manager3@example.com', name: 'Manager Three' },
      { email: 'manager4@example.com', name: 'Manager Four' },
    ];
    const manager = managers[managerNum - 1];
    if (!manager) throw new Error('Manager not found');
    const statuses = ['Open', 'In Progress', 'Closed', 'Overdue', 'Risk Accepted'];
    const riskLevels = ['High', 'Medium', 'Low'];
    const auditYears = ['2024', '2025'];
    const status = statuses[i % statuses.length];
    const riskLevel = riskLevels[i % riskLevels.length];
    const auditYear = auditYears[i % auditYears.length];
    const dueDate = new Date(2025, 2 + (i % 8), 1 + (i % 28)).toISOString().split('T')[0];
    const summaries = [
      'Implement process improvements',
      'Update documentation standards',
      'Enhance quality controls',
      'Strengthen compliance measures',
      'Optimize workflow efficiency',
      'Improve team collaboration',
      'Enhance reporting mechanisms',
      'Strengthen risk management',
    ];
    
    return {
      key: `AUDIT-4${String(i + 1).padStart(3, '0')}`,
      summary: `${summaries[i % summaries.length]} - Task ${i + 1}`,
      description: `Action item ${i + 1} assigned to ${manager.name} for team management`,
      status,
      displayStatus: status,
      dueDate,
      responsible: manager.email,
      responsibleEmail: manager.email,
      auditYear,
      auditName: `Team Audit ${managerNum}`,
      riskLevel,
    };
  }),
  // C-Level Actions - Actions for C-level executives (managing department_directors)
  ...Array.from({ length: 40 }, (_, i) => {
    const cLevels = ['CFO', 'CTO', 'COO', 'CHRO'];
    const cLevel = cLevels[i % cLevels.length];
    const deptDirectors = [
      'dept1.director@example.com',
      'dept2.director@example.com',
      'dept3.director@example.com',
      'dept4.director@example.com',
      'dept5.director@example.com',
    ];
    const responsible = deptDirectors[i % deptDirectors.length];
    const statuses = ['Open', 'In Progress', 'Closed', 'Overdue'];
    const riskLevels = ['High', 'Medium', 'Low'];
    const auditYears = ['2024', '2025'];
    const status = statuses[i % statuses.length];
    const riskLevel = riskLevels[i % riskLevels.length];
    const auditYear = auditYears[i % auditYears.length];
    const dueDate = new Date(2025, 4 + (i % 6), 1 + (i % 28)).toISOString().split('T')[0];
    const summaries = [
      'Strategic initiative implementation',
      'Executive oversight review',
      'C-level compliance assessment',
      'Organizational transformation',
      'Executive risk management',
      'Strategic planning execution',
    ];
    
    return {
      key: `AUDIT-C${String(i + 1).padStart(3, '0')}`,
      summary: `${summaries[i % summaries.length]} - ${cLevel}`,
      description: `C-level action ${i + 1} for ${cLevel} overseeing department operations`,
      status,
      displayStatus: status,
      dueDate,
      responsible,
      responsibleEmail: responsible,
      cLevel,
      auditYear,
      auditName: `${cLevel} Strategic Audit`,
      riskLevel,
    };
  }),
];

// Mock department director users for View As functionality
export const mockDepartmentDirectors = [
  { email: 'dept1.director@example.com', name: 'Department 1 Director' },
  { email: 'dept2.director@example.com', name: 'Department 2 Director' },
  { email: 'dept3.director@example.com', name: 'Department 3 Director' },
  { email: 'dept4.director@example.com', name: 'Department 4 Director' },
];

// Mock audit findings - comprehensive list for UX testing
export const mockAuditFindings = [
  // 2024 Findings
  {
    id: 1,
    finding_id: 'FND-001',
    finding_name: 'Inadequate Financial Controls',
    finding_description: 'Financial control procedures need enhancement to meet regulatory requirements',
    audit_type: 'Financial',
    risk_type: 'Financial',
    internal_control_element: 'Control Activities',
    country: 'Turkey',
    audit_year: '2024',
    audit_name: 'Financial Audit Q1 2024',
    risk_level: 'High',
    financial_impact: 125000,
    status: 'Open',
    created_by: 'audit@example.com',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 2,
    finding_id: 'FND-002',
    finding_name: 'IT Security Gaps',
    finding_description: 'IT security policies require updates and implementation of advanced threat detection',
    audit_type: 'IT',
    risk_type: 'Operational',
    internal_control_element: 'Control Environment',
    country: 'Turkey',
    audit_year: '2024',
    audit_name: 'IT Security Audit 2024',
    risk_level: 'Medium',
    financial_impact: 85000,
    status: 'In Progress',
    created_by: 'audit@example.com',
    created_at: '2024-02-10T00:00:00Z',
    updated_at: '2024-02-10T00:00:00Z',
  },
  {
    id: 3,
    finding_id: 'FND-003',
    finding_name: 'Vendor Management Weaknesses',
    finding_description: 'Lack of comprehensive vendor risk assessment and monitoring procedures',
    audit_type: 'Operational',
    risk_type: 'Operational',
    internal_control_element: 'Risk Assessment',
    country: 'Germany',
    audit_year: '2024',
    audit_name: 'Vendor Management Audit',
    risk_level: 'Medium',
    financial_impact: 45000,
    status: 'Open',
    created_by: 'audit@example.com',
    created_at: '2024-03-05T00:00:00Z',
    updated_at: '2024-03-05T00:00:00Z',
  },
  {
    id: 4,
    finding_id: 'FND-004',
    finding_name: 'Data Privacy Compliance Issues',
    finding_description: 'GDPR compliance gaps identified in data processing procedures',
    audit_type: 'Compliance',
    risk_type: 'Compliance',
    internal_control_element: 'Control Activities',
    country: 'UK',
    audit_year: '2024',
    audit_name: 'Data Privacy Audit',
    risk_level: 'High',
    financial_impact: 180000,
    status: 'Open',
    created_by: 'audit@example.com',
    created_at: '2024-03-20T00:00:00Z',
    updated_at: '2024-03-20T00:00:00Z',
  },
  {
    id: 5,
    finding_id: 'FND-005',
    finding_name: 'Procurement Process Inefficiencies',
    finding_description: 'Procurement approval workflows need optimization and automation',
    audit_type: 'Operational',
    risk_type: 'Operational',
    internal_control_element: 'Control Activities',
    country: 'Netherlands',
    audit_year: '2024',
    audit_name: 'Procurement Audit',
    risk_level: 'Low',
    financial_impact: 25000,
    status: 'Closed',
    created_by: 'audit@example.com',
    created_at: '2024-04-10T00:00:00Z',
    updated_at: '2024-06-15T00:00:00Z',
  },
  {
    id: 6,
    finding_id: 'FND-006',
    finding_name: 'Business Continuity Plan Gaps',
    finding_description: 'Business continuity and disaster recovery plans need updating and testing',
    audit_type: 'Operational',
    risk_type: 'Strategic',
    internal_control_element: 'Monitoring',
    country: 'Turkey',
    audit_year: '2024',
    audit_name: 'Business Continuity Audit',
    risk_level: 'High',
    financial_impact: 95000,
    status: 'In Progress',
    created_by: 'audit@example.com',
    created_at: '2024-05-01T00:00:00Z',
    updated_at: '2024-05-01T00:00:00Z',
  },
  {
    id: 7,
    finding_id: 'FND-007',
    finding_name: 'Fraud Detection System Limitations',
    finding_description: 'Current fraud detection mechanisms need enhancement with AI capabilities',
    audit_type: 'Fraud Investigation',
    risk_type: 'Financial',
    internal_control_element: 'Control Activities',
    country: 'Turkey',
    audit_year: '2024',
    audit_name: 'Fraud Investigation 2024',
    risk_level: 'High',
    financial_impact: 220000,
    status: 'Open',
    created_by: 'audit@example.com',
    created_at: '2024-05-15T00:00:00Z',
    updated_at: '2024-05-15T00:00:00Z',
  },
  {
    id: 8,
    finding_id: 'FND-008',
    finding_name: 'HR Policy Compliance Gaps',
    finding_description: 'Human resources policies need alignment with labor regulations',
    audit_type: 'Compliance',
    risk_type: 'Compliance',
    internal_control_element: 'Control Environment',
    country: 'France',
    audit_year: '2024',
    audit_name: 'HR Compliance Audit',
    risk_level: 'Medium',
    financial_impact: 55000,
    status: 'In Progress',
    created_by: 'audit@example.com',
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
  },
  // 2025 Findings
  {
    id: 9,
    finding_id: 'FND-009',
    finding_name: 'Cloud Security Configuration Issues',
    finding_description: 'Cloud infrastructure security configurations require hardening',
    audit_type: 'IT',
    risk_type: 'Operational',
    internal_control_element: 'Control Activities',
    country: 'Turkey',
    audit_year: '2025',
    audit_name: 'Cloud Security Audit 2025',
    risk_level: 'High',
    financial_impact: 150000,
    status: 'Open',
    created_by: 'audit@example.com',
    created_at: '2025-01-10T00:00:00Z',
    updated_at: '2025-01-10T00:00:00Z',
  },
  {
    id: 10,
    finding_id: 'FND-010',
    finding_name: 'Supply Chain Risk Management',
    finding_description: 'Supply chain risk assessment and mitigation strategies need development',
    audit_type: 'Operational',
    risk_type: 'Strategic',
    internal_control_element: 'Risk Assessment',
    country: 'Germany',
    audit_year: '2025',
    audit_name: 'Supply Chain Audit',
    risk_level: 'Medium',
    financial_impact: 75000,
    status: 'Open',
    created_by: 'audit@example.com',
    created_at: '2025-01-20T00:00:00Z',
    updated_at: '2025-01-20T00:00:00Z',
  },
  {
    id: 11,
    finding_id: 'FND-011',
    finding_name: 'API Security Vulnerabilities',
    finding_description: 'API endpoints lack proper authentication and rate limiting',
    audit_type: 'IT',
    risk_type: 'Operational',
    internal_control_element: 'Control Activities',
    country: 'UK',
    audit_year: '2025',
    audit_name: 'API Security Audit',
    risk_level: 'High',
    financial_impact: 110000,
    status: 'In Progress',
    created_by: 'audit@example.com',
    created_at: '2025-02-05T00:00:00Z',
    updated_at: '2025-02-05T00:00:00Z',
  },
  {
    id: 12,
    finding_id: 'FND-012',
    finding_name: 'Third-Party Risk Assessment Gaps',
    finding_description: 'Third-party vendor risk assessment process needs standardization',
    audit_type: 'Operational',
    risk_type: 'Operational',
    internal_control_element: 'Risk Assessment',
    country: 'Netherlands',
    audit_year: '2025',
    audit_name: 'Third-Party Risk Audit',
    risk_level: 'Medium',
    financial_impact: 60000,
    status: 'Open',
    created_by: 'audit@example.com',
    created_at: '2025-02-15T00:00:00Z',
    updated_at: '2025-02-15T00:00:00Z',
  },
  // 2023 Findings
  {
    id: 13,
    finding_id: 'FND-013',
    finding_name: 'Legacy System Security Issues',
    finding_description: 'Legacy systems require security updates and migration planning',
    audit_type: 'IT',
    risk_type: 'Operational',
    internal_control_element: 'Control Environment',
    country: 'Turkey',
    audit_year: '2023',
    audit_name: 'Legacy Systems Audit',
    risk_level: 'High',
    financial_impact: 200000,
    status: 'Closed',
    created_by: 'audit@example.com',
    created_at: '2023-11-10T00:00:00Z',
    updated_at: '2024-03-30T00:00:00Z',
  },
  {
    id: 14,
    finding_id: 'FND-014',
    finding_name: 'Inventory Management Inefficiencies',
    finding_description: 'Inventory tracking and management processes need automation',
    audit_type: 'Operational',
    risk_type: 'Operational',
    internal_control_element: 'Control Activities',
    country: 'Germany',
    audit_year: '2023',
    audit_name: 'Inventory Management Audit',
    risk_level: 'Medium',
    financial_impact: 40000,
    status: 'Closed',
    created_by: 'audit@example.com',
    created_at: '2023-10-05T00:00:00Z',
    updated_at: '2024-01-20T00:00:00Z',
  },
  // 2022 Findings
  {
    id: 15,
    finding_id: 'FND-015',
    finding_name: 'Payment Processing Controls',
    finding_description: 'Payment processing controls need enhancement for fraud prevention',
    audit_type: 'Financial',
    risk_type: 'Financial',
    internal_control_element: 'Control Activities',
    country: 'UK',
    audit_year: '2022',
    audit_name: 'Payment Processing Audit',
    risk_level: 'High',
    financial_impact: 300000,
    status: 'Closed',
    created_by: 'audit@example.com',
    created_at: '2022-09-15T00:00:00Z',
    updated_at: '2023-06-30T00:00:00Z',
  },
];

// Mock audit plans - comprehensive list for UX testing
export const mockAuditPlans = [
  // 2025 Plans
  {
    id: 1,
    audit_year: 2025,
    audit_type: 'Financial',
    audit_name: 'Financial Audit Q1 2025',
    audit_lead_name: 'John Doe',
    audit_lead_email: 'john.doe@example.com',
    business_unit: 'Finance',
    department: 'Accounting',
    status: 'Planned' as const,
    start_date: '2025-01-15',
    end_date: '2025-03-31',
    audit_duration_weeks: 10,
    created_at: '2024-12-01T00:00:00Z',
    updated_at: '2024-12-01T00:00:00Z',
  },
  {
    id: 2,
    audit_year: 2025,
    audit_type: 'IT',
    audit_name: 'Cloud Security Audit 2025',
    audit_lead_name: 'Jane Smith',
    audit_lead_email: 'jane.smith@example.com',
    business_unit: 'IT',
    department: 'Security',
    status: 'Planned' as const,
    start_date: '2025-02-01',
    end_date: '2025-04-30',
    audit_duration_weeks: 12,
    created_at: '2024-12-15T00:00:00Z',
    updated_at: '2024-12-15T00:00:00Z',
  },
  {
    id: 3,
    audit_year: 2025,
    audit_type: 'Operational',
    audit_name: 'Supply Chain Risk Audit',
    audit_lead_name: 'Bob Wilson',
    audit_lead_email: 'bob.wilson@example.com',
    business_unit: 'Operations',
    department: 'Supply Chain',
    status: 'Planned' as const,
    start_date: '2025-03-01',
    end_date: '2025-05-15',
    audit_duration_weeks: 10,
    created_at: '2024-12-20T00:00:00Z',
    updated_at: '2024-12-20T00:00:00Z',
  },
  {
    id: 4,
    audit_year: 2025,
    audit_type: 'Compliance',
    audit_name: 'GDPR Compliance Audit 2025',
    audit_lead_name: 'Alice Brown',
    audit_lead_email: 'alice.brown@example.com',
    business_unit: 'Legal',
    department: 'Compliance',
    status: 'Planned' as const,
    start_date: '2025-04-01',
    end_date: '2025-06-30',
    audit_duration_weeks: 12,
    created_at: '2025-01-05T00:00:00Z',
    updated_at: '2025-01-05T00:00:00Z',
  },
  {
    id: 5,
    audit_year: 2025,
    audit_type: 'IT',
    audit_name: 'API Security Audit 2025',
    audit_lead_name: 'Charlie Davis',
    audit_lead_email: 'charlie.davis@example.com',
    business_unit: 'IT',
    department: 'Development',
    status: 'Planned' as const,
    start_date: '2025-05-01',
    end_date: '2025-07-15',
    audit_duration_weeks: 10,
    created_at: '2025-01-10T00:00:00Z',
    updated_at: '2025-01-10T00:00:00Z',
  },
  {
    id: 6,
    audit_year: 2025,
    audit_type: 'Operational',
    audit_name: 'Vendor Management Audit 2025',
    audit_lead_name: 'Diana Evans',
    audit_lead_email: 'diana.evans@example.com',
    business_unit: 'Procurement',
    department: 'Vendor Relations',
    status: 'Planned' as const,
    start_date: '2025-06-01',
    end_date: '2025-08-15',
    audit_duration_weeks: 10,
    created_at: '2025-01-15T00:00:00Z',
    updated_at: '2025-01-15T00:00:00Z',
  },
  {
    id: 7,
    audit_year: 2025,
    audit_type: 'Financial',
    audit_name: 'Financial Audit Q2 2025',
    audit_lead_name: 'Frank Garcia',
    audit_lead_email: 'frank.garcia@example.com',
    business_unit: 'Finance',
    department: 'Accounting',
    status: 'Planned' as const,
    start_date: '2025-07-01',
    end_date: '2025-09-30',
    audit_duration_weeks: 12,
    created_at: '2025-02-01T00:00:00Z',
    updated_at: '2025-02-01T00:00:00Z',
  },
  {
    id: 8,
    audit_year: 2025,
    audit_type: 'Fraud Investigation',
    audit_name: 'Fraud Investigation Q1 2025',
    audit_lead_name: 'Grace Harris',
    audit_lead_email: 'grace.harris@example.com',
    business_unit: 'Internal Audit',
    department: 'Investigations',
    status: 'Planned' as const,
    start_date: '2025-01-20',
    end_date: '2025-03-20',
    audit_duration_weeks: 8,
    created_at: '2024-12-10T00:00:00Z',
    updated_at: '2024-12-10T00:00:00Z',
  },
  // 2024 Plans
  {
    id: 9,
    audit_year: 2024,
    audit_type: 'Financial',
    audit_name: 'Financial Audit Q1 2024',
    audit_lead_name: 'John Doe',
    audit_lead_email: 'john.doe@example.com',
    business_unit: 'Finance',
    department: 'Accounting',
    status: 'Completed' as const,
    start_date: '2024-01-01',
    end_date: '2024-03-31',
    audit_duration_weeks: 12,
    report_release_date: '2024-04-15',
    audit_report_rating: 'Satisfactory',
    created_at: '2023-12-01T00:00:00Z',
    updated_at: '2024-04-15T00:00:00Z',
  },
  {
    id: 10,
    audit_year: 2024,
    audit_type: 'IT',
    audit_name: 'IT Security Audit 2024',
    audit_lead_name: 'Jane Smith',
    audit_lead_email: 'jane.smith@example.com',
    business_unit: 'IT',
    department: 'Security',
    status: 'Fieldwork' as const,
    start_date: '2024-04-01',
    end_date: '2024-06-30',
    audit_duration_weeks: 12,
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2024-04-20T00:00:00Z',
  },
  {
    id: 11,
    audit_year: 2024,
    audit_type: 'Operational',
    audit_name: 'Operational Efficiency Audit',
    audit_lead_name: 'Bob Wilson',
    audit_lead_email: 'bob.wilson@example.com',
    business_unit: 'Operations',
    department: 'Process Improvement',
    status: 'Pre Closing Meeting' as const,
    start_date: '2024-05-01',
    end_date: '2024-07-15',
    audit_duration_weeks: 10,
    created_at: '2024-04-01T00:00:00Z',
    updated_at: '2024-07-10T00:00:00Z',
  },
  {
    id: 12,
    audit_year: 2024,
    audit_type: 'Compliance',
    audit_name: 'Data Privacy Compliance Audit',
    audit_lead_name: 'Alice Brown',
    audit_lead_email: 'alice.brown@example.com',
    business_unit: 'Legal',
    department: 'Compliance',
    status: 'Completed' as const,
    start_date: '2024-02-01',
    end_date: '2024-04-30',
    audit_duration_weeks: 12,
    report_release_date: '2024-05-15',
    audit_report_rating: 'Needs Improvement',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-05-15T00:00:00Z',
  },
  {
    id: 13,
    audit_year: 2024,
    audit_type: 'Financial',
    audit_name: 'Financial Audit Q2 2024',
    audit_lead_name: 'Charlie Davis',
    audit_lead_email: 'charlie.davis@example.com',
    business_unit: 'Finance',
    department: 'Accounting',
    status: 'Closing Meeting' as const,
    start_date: '2024-04-01',
    end_date: '2024-06-30',
    audit_duration_weeks: 12,
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2024-06-25T00:00:00Z',
  },
  {
    id: 14,
    audit_year: 2024,
    audit_type: 'IT',
    audit_name: 'IT Infrastructure Audit',
    audit_lead_name: 'Diana Evans',
    audit_lead_email: 'diana.evans@example.com',
    business_unit: 'IT',
    department: 'Infrastructure',
    status: 'Completed' as const,
    start_date: '2024-03-01',
    end_date: '2024-05-31',
    audit_duration_weeks: 12,
    report_release_date: '2024-06-15',
    audit_report_rating: 'Satisfactory',
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-06-15T00:00:00Z',
  },
  {
    id: 15,
    audit_year: 2024,
    audit_type: 'Operational',
    audit_name: 'Vendor Management Audit',
    audit_lead_name: 'Frank Garcia',
    audit_lead_email: 'frank.garcia@example.com',
    business_unit: 'Procurement',
    department: 'Vendor Relations',
    status: 'Fieldwork' as const,
    start_date: '2024-06-01',
    end_date: '2024-08-31',
    audit_duration_weeks: 12,
    created_at: '2024-05-01T00:00:00Z',
    updated_at: '2024-07-15T00:00:00Z',
  },
  {
    id: 16,
    audit_year: 2024,
    audit_type: 'Fraud Investigation',
    audit_name: 'Fraud Investigation Q2 2024',
    audit_lead_name: 'Grace Harris',
    audit_lead_email: 'grace.harris@example.com',
    business_unit: 'Internal Audit',
    department: 'Investigations',
    status: 'Completed' as const,
    start_date: '2024-04-01',
    end_date: '2024-06-15',
    audit_duration_weeks: 10,
    report_release_date: '2024-06-30',
    audit_report_rating: 'Satisfactory',
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2024-06-30T00:00:00Z',
  },
  // 2023 Plans
  {
    id: 17,
    audit_year: 2023,
    audit_type: 'Financial',
    audit_name: 'Financial Audit Q1 2023',
    audit_lead_name: 'John Doe',
    audit_lead_email: 'john.doe@example.com',
    business_unit: 'Finance',
    department: 'Accounting',
    status: 'Completed' as const,
    start_date: '2023-01-01',
    end_date: '2023-03-31',
    audit_duration_weeks: 12,
    report_release_date: '2023-04-15',
    audit_report_rating: 'Satisfactory',
    created_at: '2022-12-01T00:00:00Z',
    updated_at: '2023-04-15T00:00:00Z',
  },
  {
    id: 18,
    audit_year: 2023,
    audit_type: 'IT',
    audit_name: 'Legacy Systems Security Audit',
    audit_lead_name: 'Jane Smith',
    audit_lead_email: 'jane.smith@example.com',
    business_unit: 'IT',
    department: 'Infrastructure',
    status: 'Completed' as const,
    start_date: '2023-05-01',
    end_date: '2023-07-31',
    audit_duration_weeks: 12,
    report_release_date: '2023-08-15',
    audit_report_rating: 'Needs Improvement',
    created_at: '2023-04-01T00:00:00Z',
    updated_at: '2023-08-15T00:00:00Z',
  },
  {
    id: 19,
    audit_year: 2023,
    audit_type: 'Operational',
    audit_name: 'Inventory Management Audit',
    audit_lead_name: 'Bob Wilson',
    audit_lead_email: 'bob.wilson@example.com',
    business_unit: 'Operations',
    department: 'Logistics',
    status: 'Completed' as const,
    start_date: '2023-08-01',
    end_date: '2023-10-31',
    audit_duration_weeks: 12,
    report_release_date: '2023-11-15',
    audit_report_rating: 'Satisfactory',
    created_at: '2023-07-01T00:00:00Z',
    updated_at: '2023-11-15T00:00:00Z',
  },
  // 2022 Plans
  {
    id: 20,
    audit_year: 2022,
    audit_type: 'Financial',
    audit_name: 'Financial Audit 2022',
    audit_lead_name: 'John Doe',
    audit_lead_email: 'john.doe@example.com',
    business_unit: 'Finance',
    department: 'Accounting',
    status: 'Completed' as const,
    start_date: '2022-01-01',
    end_date: '2022-12-31',
    audit_duration_weeks: 52,
    report_release_date: '2023-02-15',
    audit_report_rating: 'Satisfactory',
    created_at: '2021-12-01T00:00:00Z',
    updated_at: '2023-02-15T00:00:00Z',
  },
  {
    id: 21,
    audit_year: 2022,
    audit_type: 'Financial',
    audit_name: 'Payment Processing Audit',
    audit_lead_name: 'Alice Brown',
    audit_lead_email: 'alice.brown@example.com',
    business_unit: 'Finance',
    department: 'Payments',
    status: 'Completed' as const,
    start_date: '2022-06-01',
    end_date: '2022-09-30',
    audit_duration_weeks: 16,
    report_release_date: '2022-10-15',
    audit_report_rating: 'Satisfactory',
    created_at: '2022-05-01T00:00:00Z',
    updated_at: '2022-10-15T00:00:00Z',
  },
  // 2021 Plans
  {
    id: 22,
    audit_year: 2021,
    audit_type: 'Financial',
    audit_name: 'Financial Audit 2021',
    audit_lead_name: 'John Doe',
    audit_lead_email: 'john.doe@example.com',
    business_unit: 'Finance',
    department: 'Accounting',
    status: 'Completed' as const,
    start_date: '2021-01-01',
    end_date: '2021-12-31',
    audit_duration_weeks: 52,
    report_release_date: '2022-02-15',
    audit_report_rating: 'Satisfactory',
    created_at: '2020-12-01T00:00:00Z',
    updated_at: '2022-02-15T00:00:00Z',
  },
];

// Mock dropdown options
export const mockDropdownOptions = {
  'audit_type': ['Financial', 'IT', 'Operational', 'Compliance', 'Fraud Investigation'],
  'audit_year': ['2020', '2021', '2022', '2023', '2024', '2025'],
  'risk_type': ['Financial', 'Operational', 'Compliance', 'Strategic', 'Reputational'],
  'internal_control_element': [
    'Control Environment',
    'Risk Assessment',
    'Control Activities',
    'Information & Communication',
    'Monitoring',
  ],
  'country': ['Turkey', 'Germany', 'UK', 'Netherlands', 'France'],
  'risk_level': ['High', 'Medium', 'Low'],
  'status': ['Open', 'In Progress', 'Closed', 'Risk Accepted'],
  'clevel': ['CEO', 'CFO', 'CTO', 'COO'],
};

// Mock overdue and upcoming actions
export const mockOverdueActions = mockFindingActions.filter(a => 
  a.status === 'Open' && a.dueDate && new Date(a.dueDate) < new Date()
);

export const mockUpcomingActions = mockFindingActions.filter(a => {
  if (!a.dueDate) return false;
  const dueDate = new Date(a.dueDate);
  const today = new Date();
  const daysDiff = Math.ceil((dueDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
  return daysDiff > 0 && daysDiff <= 30;
});

// Export helper function
export const getMockData = async <T>(_key: string, data: T, ms: number = 150): Promise<T> => {
  await delay(ms);
  return data;
};

